
name: Update README.md

on:
  push:
    branches:
      - main
  schedule:
    # 每天下午5点下班更新
    - cron: "30 * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update this repo's README
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_PROJECTS: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LOC_CHART: false
          SHOW_SHORT_INFO: false
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_LINES_OF_CODE: true
          SHOW_TIMEZONE: true
          SHOW_EDITORS: true
