
name: Update README.md

on:
  push:
    # 只有推送到 main 分支才会触发
    branches:
      - main
  schedule:
    # 每天早上五点，自动触发
    - cron: "* * * * *"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Update this repo's README
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.TOKEN }}
          WAKATIME_TOKEN: ${{ secrets.WAKATIME_TOKEN }}
          SHOW_PROJECTS: false
          SHOW_PROFILE_VIEWS: false
          SHOW_COMMIT: false
          SHOW_LANGUAGE_PER_REPO: false
          SHOW_DAYS_OF_WEEK: false
          SHOW_LOC_CHART: false
          SHOW_LINES_OF_CODE: true
          SHOW_SHORT_INFO: false
